package com.example.submissiondikoding

object BuahData {

    private var data = arrayOf(
        arrayOf(
            "Apple",
            "Central Asia",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/330px-Pink_lady_and_cross_section.jpg",
            "An apple is an edible fruit produced by an apple tree (Malus domestica). Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today. Apples have been grown for thousands of years in Asia and Europe and were brought to North America by European colonists. Apples have religious and mythological significance in many cultures, including Norse, Greek, and European Christian tradition.\n" +
                    "\n" +
                    "Apples grown from seed tend to be very different from those of their parents, and the resultant fruit frequently lacks desired characteristics. Generally, apple cultivars are propagated by clonal grafting onto rootstocks. Apple trees grown without rootstocks tend to be larger and much slower to fruit after planting. Rootstocks are used to control the speed of growth and the size of the resulting tree, allowing for easier harvesting.\n" +
                    "\n" +
                    "There are more than 7,500 known cultivars of apples. Different cultivars are bred for various tastes and uses, including cooking, eating raw, and cider production. Trees and fruit are prone to a number of fungal, bacterial, and pest problems, which can be controlled by a number of organic and non-organic means. In 2010, the fruit's genome was sequenced as part of research on disease control and selective breeding in apple production.\n" +
                    "\n" +
                    "Worldwide production of apples in 2018 was 86 million tonnes, with China accounting for nearly half of the total"
        ),
        arrayOf("Orange","China","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg","An orange is a fruit of various citrus species in the family Rutaceae (see list of plants known as orange); it primarily refers to Citrus × sinensis,[1] which is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange. The sweet orange reproduces asexually (apomixis through nucellar embryony); varieties of sweet orange arise through mutations.[2][3][4][5]\n" +
                "\n" +
                "The orange is a hybrid between pomelo (Citrus maxima) and mandarin (Citrus reticulata).[2][6] The chloroplast genome, and therefore the maternal line, is that of pomelo.[7] The sweet orange has had its full genome sequenced.[2]\n" +
                "\n" +
                "The orange originated in a region encompassing Southern China, Northeast India, and Myanmar,[8][9] and the earliest mention of the sweet orange was in Chinese literature in 314 BC.[2] As of 1987, orange trees were found to be the most cultivated fruit tree in the world.[10] Orange trees are widely grown in tropical and subtropical climates for their sweet fruit. The fruit of the orange tree can be eaten fresh, or processed for its juice or fragrant peel.[11] As of 2012, sweet oranges accounted for approximately 70% of citrus production.[12]\n" +
                "\n" +
                "In 2019, 79 million tonnes of oranges were grown worldwide, with Brazil producing 22% of the total, followed by China and India"),
        arrayOf("mango","Southeast Asia","https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hapus_Mango.jpg/330px-Hapus_Mango.jpg","A mango is an edible stone fruit produced by the tropical tree Mangifera indica which is believed to have originated in India.[1] M. indica has been cultivated in South and Southeast Asia since ancient times resulting in two types of modern mango cultivars: the \"Indian type\" and the \"Southeast Asian type\".[2][3] Other species in the genus Mangifera also produce edible fruits that are also called \"mangoes\", the majority of which are found in the Malesian ecoregion.[4]\n" +
                "\n" +
                "Worldwide, there are several hundred cultivars of mango. Depending on the cultivar, mango fruit varies in size, shape, sweetness, skin color, and flesh color which may be pale yellow, gold, green, or orange.[1] Mango is the national fruit of India, Pakistan and the Philippines,[5][6] while the mango tree is the national tree of Bangladesh"),
        arrayOf("Avocado","America","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Avocado_Hass_-_single_and_halved.jpg/330px-Avocado_Hass_-_single_and_halved.jpg","The avocado (Persea americana) is a tree originating in the Americas which is likely native to the highland regions of south-central Mexico to Guatemala.[3][4][5] It is classified as a member of the flowering plant family Lauraceae.[3] The fruit of the plant, also called an avocado (or avocado pear or alligator pear), is botanically a large berry containing a single large seed.[6] Avocado trees are partially self-pollinating, and are often propagated through grafting to maintain predictable fruit quality and quantity.[7]\n" +
                "\n" +
                "Avocados are cultivated in tropical and Mediterranean climates of many countries,[3] with Mexico as the leading producer of avocados in 2019, supplying 32% of the world total.[8] Avocado production is one of the most environmentally intensive fruits, using 70 litres (18 US gallons; 15 imperial gallons) of water per avocado,[9] and over 400 grams of CO2 emissions.[10] In major production regions like Chile, Mexico and California, the water demands for avocado puts pressure on overall water resources.[11] Avocado production is also connected to other concerns, including environmental justice and human rights concerns, deforestation and connections of Mexican avocados with organized crime.[12][13][14][15] Climate change is expected to cause significant changes in the suitable growing zones for avocados, and put additional pressure due to heat waves and drought.[16][17]\n" +
                "\n" +
                "The fruit of domestic varieties has a buttery flesh when ripe. Depending on the variety, avocados have green, brown, purplish, or black skin when ripe, and may be pear-shaped, egg-shaped, or spherical. Commercially, the fruits are picked while immature, and ripened after harvesting. The high fat and smooth texture of avocados make it a useful and diverse food in different cuisines, and is traditionally important in Mexican foods. The high nutritional value and concentration of fat, make avocados a commonly used food in vegetarian foods and generally is thought nutritious and healthy"),
        arrayOf("Grape","Middle East","https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Table_grapes_on_white.jpg/330px-Table_grapes_on_white.jpg","A grape is a fruit, botanically a berry, of the deciduous woody vines of the flowering plant genus Vitis.\n" +
                "\n" +
                "Grapes can be eaten fresh as table grapes, used for making wine, jam, grape juice, jelly, grape seed extract, vinegar, and grape seed oil, or dried as raisins, currants and sultanas. Grapes are a non-climacteric type of fruit, generally occurring in clusters."),
        arrayOf("Strawberry","France","https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/330px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg","The garden strawberry (or simply strawberry; Fragaria × ananassa)[1] is a widely grown hybrid species of the genus Fragaria, collectively known as the strawberries, which are cultivated worldwide for their fruit. The fruit is widely appreciated for its characteristic aroma, bright red color, juicy texture, and sweetness. It is consumed in large quantities, either fresh or in such prepared foods as jam, juice, pies, ice cream, milkshakes, and chocolates. Artificial strawberry flavorings and aromas are also widely used in products such as candy, soap, lip gloss, perfume, and many others.\n" +
                "\n" +
                "The garden strawberry was first bred in Brittany, France, in the 1750s via a cross of Fragaria virginiana from eastern North America and Fragaria chiloensis, which was brought from Chile by Amédée-François Frézier in 1714.[2] Cultivars of Fragaria × ananassa have replaced, in commercial production, the woodland strawberry (Fragaria vesca), which was the first strawberry species cultivated in the early 17th century.[3]\n" +
                "\n" +
                "The strawberry is not, from a botanical point of view, a berry. Technically, it is an aggregate accessory fruit, meaning that the fleshy part is derived not from the plant's ovaries but from the receptacle that holds the ovaries.[4] Each apparent \"seed\" (achene) on the outside of the fruit is actually one of the ovaries of the flower, with a seed inside it.[4]\n" +
                "\n" +
                "In 2019, world production of strawberries was 9 million tonnes, led by China with 40% of the total"),
        arrayOf("Lemon","Asia","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/330px-P1030323.JPG","The lemon (Citrus limon) is a species of small evergreen trees in the flowering plant family Rutaceae, native to Asia, primarily Northeast India (Assam), Northern Myanmar or China.[2]\n" +
                "\n" +
                "The tree's ellipsoidal yellow fruit is used for culinary and non-culinary purposes throughout the world, primarily for its juice, which has both culinary and cleaning uses.[2] The pulp and rind are also used in cooking and baking. The juice of the lemon is about 5% to 6% citric acid, with a pH of around 2.2, giving it a sour taste. The distinctive sour taste of lemon juice makes it a key ingredient in drinks and foods such as lemonade and lemon meringue pie."),
        arrayOf("Banana","Tropical Indomalaya","https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Banana_and_cross_section.jpg/375px-Banana_and_cross_section.jpg","A banana is an elongated, edible fruit – botanically a berry[1][2] – produced by several kinds of large herbaceous flowering plants in the genus Musa.[3] In some countries, bananas used for cooking may be called \"plantains\", distinguishing them from dessert bananas. The fruit is variable in size, color, and firmness, but is usually elongated and curved, with soft flesh rich in starch covered with a rind, which may be green, yellow, red, purple, or brown when ripe. The fruits grow upward in clusters near the top of the plant. Almost all modern edible seedless (parthenocarp) bananas come from two wild species – Musa acuminata and Musa balbisiana. The scientific names of most cultivated bananas are Musa acuminata, Musa balbisiana, and Musa × paradisiaca for the hybrid Musa acuminata × M. balbisiana, depending on their genomic constitution. The old scientific name for this hybrid, Musa sapientum, is no longer used.\n" +
                "\n" +
                "Musa species are native to tropical Indomalaya and Australia, and are likely to have been first domesticated in Papua New Guinea.[4][5] They are grown in 135 countries,[6] primarily for their fruit, and to a lesser extent to make fiber, banana wine, and banana beer and as ornamental plants. The world's largest producers of bananas in 2017 were India and China, which together accounted for approximately 38% of total production.[7]\n" +
                "\n" +
                "Worldwide, there is no sharp distinction between \"bananas\" and \"plantains\". Especially in the Americas and Europe, \"banana\" usually refers to soft, sweet, dessert bananas, particularly those of the Cavendish group, which are the main exports from banana-growing countries. By contrast, Musa cultivars with firmer, starchier fruit are called \"plantains\". In other regions, such as Southeast Asia, many more kinds of banana are grown and eaten, so the binary distinction is not as useful and is not made in local languages.\n" +
                "\n" +
                "The term \"banana\" is also used as the common name for the plants that produce the fruit.[3] This can extend to other members of the genus Musa, such as the scarlet banana (Musa coccinea), the pink banana (Musa velutina), and the Fe'i bananas. It can also refer to members of the genus Ensete, such as the snow banana (Ensete glaucum) and the economically important false banana (Ensete ventricosum). Both genera are in the banana family, Musaceae"),
        arrayOf("Blueberry","North America","https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Blueberries.jpg/330px-Blueberries.jpg","Blueberries are a widely distributed and widespread group of perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium. Vaccinium also includes cranberries, bilberries, huckleberries and Madeira blueberries.[1] Commercial blueberries—both wild (lowbush) and cultivated (highbush)—are all native to North America. The highbush varieties were introduced into Europe during the 1930s.[2]\n" +
                "\n" +
                "Blueberries are usually prostrate shrubs that can vary in size from 10 centimeters (4 inches) to 4 meters (13 feet) in height. In commercial production of blueberries, the species with small, pea-size berries growing on low-level bushes are known as \"lowbush blueberries\" (synonymous with \"wild\"), while the species with larger berries growing on taller, cultivated bushes are known as \"highbush blueberries\". Canada is the leading producer of lowbush blueberries, while the United States produces some 40% of the world supply of highbush blueberries."),
        arrayOf("Salak","Indonesia","https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Salak_%28Salacca_zalacca%29%2C_2015-05-17.jpg/330px-Salak_%28Salacca_zalacca%29%2C_2015-05-17.jpg","Salak (Salacca zalacca) is a species of palm tree (family Arecaceae) native to Java and Sumatra in Indonesia. It is cultivated in other regions of Indonesia as a food crop, and reportedly naturalized in Bali, Lombok, Timor, Maluku, and Sulawesi.[1][2]\n" +
                "\n" +
                "The salak Salacca glabrecens was featured on a Malaysian stamp, issued 27 February 1999 under the rare fruits series of stamps.[3]\n" +
                "\n" +
                "\n" +
                "Salak exported from Indonesia\n" +
                "It is a very short-stemmed palm, with leaves up to 6 metres (20 ft) long; each leaf has a 2-metre long petiole with spines up to 15 centimetres (5.9 in) long, and numerous leaflets. The fruits grow in clusters at the base of the palm, and are also known as snake fruit due to the reddish-brown scaly skin. They are about the size and shape of a ripe fig, with a distinct tip. The pulp is edible. The fruit can be peeled by pinching the tip, which should cause the skin to slough off so it can be pulled away. The fruit inside consists of three lobes with the two larger ones, or even all three, containing a large inedible seed. The lobes resemble, and have the consistency of, large peeled garlic cloves. The taste is usually sweet and acidic, with a strong astringent edge, but its apple-like texture can vary from very dry and crumbly (salak pondoh from Yogyakarta) to moist and crunchy (salak Bali)."),
    )
    val listData: ArrayList<Buah>
        get() {
            val list = ArrayList<Buah>()
            for (aData in data) {
                val buah = Buah()
                buah.name = aData[0]
                buah.asal = aData[1]
                buah.photo = aData[2]
                buah.desc = aData[3]

                list.add(buah)
            }
            return list
        }
}